version: '3.8'

services:
  pr_test_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-pr
    container_name: laravel-pr
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      DB_HOST: pr_test_mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: pr_test_redis
    ports:
      - "9000:9000"
    depends_on:
      - pr_test_mysql
      - pr_test_redis

  pr_test_nginx:
    image: nginx:stable-alpine
    container_name: pr_test_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pr_test_app

  pr_test_mysql:
    image: mysql:8.0
    container_name: pr_test_mysql
    ports:
      - "8800:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql_data:/var/lib/mysql

  pr_test_redis:
    image: redis:alpine
    container_name: pr_test_redis
    ports:
      - "6381:6379"

volumes:
  mysql_data:
